language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - apt-get update && apt-get install -y rpm
  - pip install pylint pylint_runner ordereddict mysqlclient requests feedparser prometheus_client
script:
  - cd rpm && make all && cd ..
  - pylint_runner --rcfile .pylintrc
  - ./tests.py
